# Generated by Django 5.0.6 on 2024-05-24 05:44

import django.db.models.deletion
import extention.name_fixer
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Conversation_id', models.UUIDField(default=uuid.uuid4)),
                ('displayـname', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=32)),
                ('is_private', models.BooleanField(default=True)),
                ('chat_type', models.IntegerField(choices=[(1, 'Private'), (2, 'Group'), (3, 'Channel')])),
                ('profile_photo', models.ImageField(upload_to=extention.name_fixer.upload_img_path)),
                ('description', models.CharField(max_length=512)),
                ('extra_details', models.TextField()),
                ('members', models.ManyToManyField(related_name='memeber', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('msg_type', models.IntegerField(choices=[(1, 'Text'), (2, 'Gif'), (3, 'Voice'), (4, 'Pic'), (5, 'Video'), (6, 'Music')], default=1)),
                ('content', models.TextField()),
                ('is_edited', models.BooleanField(default=False)),
                ('is_forwarded', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('chat_id', models.ManyToManyField(related_name='message', to='chat.conversation')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Seen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seen',
                'verbose_name_plural': 'Seens',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='seens',
            field=models.ManyToManyField(blank=True, related_name='seen', through='chat.Seen', to=settings.AUTH_USER_MODEL),
        ),
    ]
